admin_dimrdv_config:
    path: /admin/dimrdv/config
    defaults:
        _controller: Iepiep\Dimrdv\Controller\Admin\AdminDimrdvConfigController::indexAction
        _legacy_controller: AdminDimrdvConfig
    requirements:
        _legacy_controller: AdminDimrdvConfig

admin_dimrdv_gestionrdv_index:
    path: /admin/dimrdv/gestionrdv
    defaults:
        _controller: Iepiep\Dimrdv\Controller\Admin\AdminDimrdvGestionRdvController::indexAction
        _legacy_controller: AdminDimrdvGestionRdv
    requirements:
        _legacy_controller: AdminDimrdvGestionRdv

admin_dimrdv_itinerary_index:
    path: /admin/dimrdv/itinerary
    defaults:
        _controller: Iepiep\Dimrdv\Controller\Admin\AdminDimrdvItineraryController::indexAction
        _legacy_controller: AdminDimrdvItinerary
    requirements:
        _legacy_controller: AdminDimrdvItinerary
