admin_dimrdv_config:
    path: /admin/dimrdv/config
    defaults:
        _controller: Iepiep\Dimrdv\Controller\Admin\AdminDimrdvConfigController::indexAction

admin_dimrdv_gestionrdv_index:
    path: /admin/dimrdv/gestionrdv
    defaults:
        _controller: Iepiep\Dimrdv\Controller\Admin\AdminDimrdvGestionRdvController::indexAction

admin_dimrdv_itinerary_index:
    path: /admin/dimrdv/itinerary
    defaults:
        _controller: Iepiep\Dimrdv\Controller\Admin\AdminDimrdvItineraryController::indexAction